# Specify image version
FROM python:3.11-slim

# Define working directory
WORKDIR /app

# Copy backend dependencies
COPY requirements.txt ./

# Install backend dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy backend code
COPY . .

# Expose port
EXPOSE 5000

# Execute program
CMD [ "python", "app.py" ]
# CMD ["gunicorn", "--bind", "0.0.0.0:5000", "app:app"]